### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by lgarron** [cubing/live.cubing.net#2]
Since this site will be handling logins and user data, let's get this right from the start:
- HTTPS
- HSTS + [Preload](https://hstspreload.appspot.com/): `Strict-Transport-Security: max-age=16070400; includeSubDomains; preload`

**Comment by jfly** [comment]
This is largely done, we're just waiting on sslMate to give us a certificate, as opposed to the one we generated on the server for testing purposes.
